### ISSUE TITLE
There was an error when trying to short the URL: b'Error

### ISSUE THREAD

**Issue by aki2419** [PerezMascato/URLCADIZ#5]
Post LINK: new-video-in-youtube-this-is-a-perez-mascato-i-love

Traceback (most recent call last):

  File "URLCADIZ.py", line 180, in <module>

    Main()

  File "URLCADIZ.py", line 24, in Main

    Selector()

  File "URLCADIZ.py", line 32, in Selector

    EnlaceYoutube()

  File "URLCADIZ.py", line 80, in EnlaceYoutube

    EndLink = Shortener.tinyurl.short(OriginalLink)

  File "/home/blackout/.local/lib/python3.8/site-packages/pyshorteners/shorteners/tinyurl.py", line 37, in short

    raise ShorteningErrorException(response.content)

pyshorteners.exceptions.ShorteningErrorException: There was an error on trying to short the url: b'Error'

**Comment by PerezMascato** [comment]
You can change my code
